### ISSUE TITLE
Update presentations folder with new presentations

### ISSUE THREAD

**Issue by magitz** [PracticumAI/deep_learning#47]

**Comment by ilutticken** [comment]
Do you want the originals moved to an archival folder? If so, here or on Teams?

**Comment by magitz** [comment]
Archive on Teams

**Comment by ilutticken** [comment]
Old files archived, new files (up to M3) are in _**reorg**_.

**Comment by magitz** [comment]
Presentations 1-3 have been edited and updated in main. Still need to work on presentation 4.

**Comment by magitz** [comment]
There is no 4th presentation ;-)

PDFs are updated. Will merge into main.
